'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {normalize,matches}=require('../board/filter.js');
const root=path.join(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'board/index.json'),'utf8'));
const audit=JSON.parse(fs.readFileSync(path.join(root,'board/audit.json'),'utf8'));
const base={company:'',brand:'',catalog:'',collection:'',year:'',month:'',evidence:'',from:'',to:'',query:''};
const filter=(kind,f)=>data.rows.filter(r=>r.kind===kind&&matches(r,{...base,...f},r.search));
assert.equal(new Set(data.rows.map(r=>r.id)).size,data.rows.length);
for(const [kind,count]of Object.entries({products:24147,documents:689,pages:16819,codes:24965,brochures:112}))assert.equal(filter(kind,{}).length,count,kind);
assert.equal(audit.embedded_images,56960);
assert.equal(audit.text_files,242);
assert.equal(Object.keys(audit.inputs).filter(p=>p.endsWith('/text.jsonl')).length,689);
assert.equal(Object.keys(audit.inputs).filter(p=>p.includes('/exports/')).length,36);
for(const [company,count]of Object.entries(data.counts))assert.equal(filter('products',{company}).length,count);
const products=filter('products',{company:'Texdecor'}).filter(r=>r.catalogs.length);assert.equal(products.length,2700);assert.equal(products.reduce((n,r)=>n+r.catalogs.length,0),15314);
assert(filter('documents',{query:'slimwall fragment',year:'2023',month:'09'}).length>=2);
assert(filter('documents',{query:'airpanel',year:'2017',month:'10'}).length>=4);
assert(filter('brochures',{year:'2026',month:'09'}).length);
assert(filter('products',{catalog:products[0].catalogs[0],company:'Texdecor',brand:products[0].brand}).includes(products[0]));
assert(filter('images',{catalog:products[0].catalogs[0]}).length);
assert(filter('products',{year:'unknown'}).every(r=>r.dateValues.length===0));
const r={company:'Texdecor',brand:'Texdecor',catalogs:['a'],collections:['b'],dateValues:['2023-09','2024-02','2026'],search:'slimwall fragment'};
assert(matches(r,{...base,year:'2023',month:'09',from:'2023-08',to:'2023-10',catalog:'a',collection:'b'}));
assert(!matches(r,{...base,year:'2023',month:'02'}));
assert(!matches(r,{...base,from:'2023-10',to:'2023-08'}));
assert(!matches(r,{...base,year:'2026',month:'01'}));
assert(!matches(r,{...base,year:'unknown',from:'2023-01'}));
assert(!matches(r,{...base,catalog:'other'}));
assert.equal(normalize('Création'),'creation');
console.log('PASS: import totals, IDs, 36 exports / 689 texts / 242 originals, all companies, direct Texdecor relationships, SlimWall 09/2023, AirPanel 10/2017, brochures, monthly period intersection, linked product and image filters.');
